//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.ActionLog1 = new HashSet<ActionLog1>();
            this.ParticipantAction = new HashSet<ParticipantAction>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string MethodName { get; set; }
        public string Notes { get; set; }
        public int TypeId { get; set; }
        public int ActivityFromId { get; set; }
        public int ActivityToId { get; set; }
        public string TimeInterval { get; set; }
        public Nullable<int> TimerActionId { get; set; }
        public string ConditionValue { get; set; }
        public string ConfirmationMessage { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ActionType ActionType { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual Activity Activity1 { get; set; }
        public virtual TimerAction TimerAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionLog1> ActionLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantAction> ParticipantAction { get; set; }
    }
}
