//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog1
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int ActivityInstanceFromId { get; set; }
        public int ActivityInstanceToId { get; set; }
        public int ActionId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ParticipantId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Action Action { get; set; }
        public virtual ActivityInstance ActivityInstance { get; set; }
        public virtual ActivityInstance ActivityInstance1 { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual Task1 Task1 { get; set; }
    }
}
