//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Action = new HashSet<Action>();
            this.Action1 = new HashSet<Action>();
            this.ActivityInstance = new HashSet<ActivityInstance>();
            this.Participant = new HashSet<Participant>();
            this.Participant1 = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int ProcessId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> WaitRuleId { get; set; }
        public string SourceCode { get; set; }
        public string ConditionExpression { get; set; }
        public Nullable<int> ThreadNumber { get; set; }
        public Nullable<int> StartProcessTypeId { get; set; }
        public Nullable<int> ProcessStartModeId { get; set; }
        public string AdditionalParameters { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action1 { get; set; }
        public virtual Process Process { get; set; }
        public virtual ProcessStartMode ProcessStartMode { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        public virtual ActivityType ActivityType { get; set; }
        public virtual WaitRule WaitRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityInstance> ActivityInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participant1 { get; set; }
    }
}
