//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public int ContactId { get; set; }
        public int AddressTypeId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public string Address1 { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public string PhoneNum { get; set; }
        public string FaxNum { get; set; }
        public string ExtNum { get; set; }
        public string Notes { get; set; }
    
        public virtual AddressType AddressType { get; set; }
        public virtual State State { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Country Country { get; set; }
    }
}
