//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attorney1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attorney1()
        {
            this.AttorneyAlert = new HashSet<AttorneyAlert>();
            this.AttorneyComment = new HashSet<AttorneyComment>();
            this.ClientAttorney = new HashSet<ClientAttorney>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AttorneyStatusId { get; set; }
        public Nullable<System.DateTime> PartnerDate { get; set; }
        public Nullable<int> PartnerTypeId { get; set; }
        public Nullable<int> AttorneyTypeId { get; set; }
    
        public virtual AttorneyStatus1 AttorneyStatus1 { get; set; }
        public virtual AttorneyType1 AttorneyType1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttorneyAlert> AttorneyAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttorneyComment> AttorneyComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAttorney> ClientAttorney { get; set; }
    }
}
