//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attorney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attorney()
        {
            this.MatterAttorney = new HashSet<MatterAttorney>();
            this.Pitch = new HashSet<Pitch>();
            this.PitchAttorneyRole = new HashSet<PitchAttorneyRole>();
            this.PitchAttorneyRole1 = new HashSet<PitchAttorneyRole>();
            this.Waiver = new HashSet<Waiver>();
            this.Waiver1 = new HashSet<Waiver>();
        }
    
        public int UserId { get; set; }
        public string AtMf { get; set; }
        public string AtInit { get; set; }
        public Nullable<int> AttorneyStatusId { get; set; }
        public string CatId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string AtMailStop { get; set; }
        public int AttorneyPartnerTypeId { get; set; }
        public Nullable<System.DateTime> PartnerDate { get; set; }
        public Nullable<int> AtClassYear { get; set; }
        public Nullable<System.DateTime> AtDob { get; set; }
        public string AtDobCity { get; set; }
        public string AtDobSt { get; set; }
        public string AtDobCountry { get; set; }
        public string MsId { get; set; }
        public string AtSoc { get; set; }
        public string PcDocid { get; set; }
        public string AtComment { get; set; }
        public string AtConfComment { get; set; }
        public string AtService { get; set; }
        public Nullable<int> AtCaseLocationId { get; set; }
    
        public virtual AttorneyPartnerType AttorneyPartnerType { get; set; }
        public virtual AttorneyStatus AttorneyStatus { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterAttorney> MatterAttorney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pitch> Pitch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchAttorneyRole> PitchAttorneyRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchAttorneyRole> PitchAttorneyRole1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waiver> Waiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waiver> Waiver1 { get; set; }
    }
}
