//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Thread { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string Host { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
        public int RequestId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionDescription { get; set; }
        public string Target { get; set; }
        public string Comments { get; set; }
    }
}
