//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail1
    {
        public int Id { get; set; }
        public string RateDescription { get; set; }
        public Nullable<int> DisbRateId { get; set; }
        public string EbillingReferenceNo { get; set; }
        public string VatNo { get; set; }
        public Nullable<int> BillFormatId { get; set; }
        public Nullable<int> MatterCategoryId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> CibcBank { get; set; }
        public Nullable<decimal> PercentageBankPaid { get; set; }
        public Nullable<decimal> PercentageClientPaid { get; set; }
        public Nullable<int> TaxJurisdictionId { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<bool> IsExemptFromFee { get; set; }
        public Nullable<int> PrebillFormatId { get; set; }
        public Nullable<int> MatterId { get; set; }
        public Nullable<bool> IsEbilling { get; set; }
        public Nullable<bool> IsFeeRatePopulated { get; set; }
        public Nullable<bool> IsDisbRatePopulated { get; set; }
        public Nullable<int> LevySurchargeId { get; set; }
        public Nullable<decimal> EstimatedDollarAmount { get; set; }
        public Nullable<bool> HasFeesArrangement { get; set; }
        public Nullable<int> FeesTypeId { get; set; }
        public string FeesDescription { get; set; }
        public Nullable<int> FeesArrangementId { get; set; }
        public Nullable<decimal> FeesAmount { get; set; }
        public Nullable<bool> HasRetainerFees { get; set; }
        public Nullable<decimal> RetainerFeesAmount { get; set; }
        public Nullable<int> RetainerFeesTypeId { get; set; }
        public string RetainerFeesDescription { get; set; }
        public Nullable<bool> HasAuthorizationDocument { get; set; }
        public Nullable<int> RetainerApproverId { get; set; }
        public string RetainerApproverComment { get; set; }
        public string WaiverCmment { get; set; }
        public Nullable<bool> IsRetainerApproved { get; set; }
        public Nullable<bool> IsBudgetEstimate { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public Nullable<bool> IsStandardHourlyRate { get; set; }
        public Nullable<int> SpecialFeeArrangementId { get; set; }
        public Nullable<decimal> FixedFee { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<decimal> MonthlyRetainer { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> QuarterlyRetainer { get; set; }
        public string RentableSquareFoot { get; set; }
        public Nullable<bool> HasSpecialAuthorizationDocument { get; set; }
        public Nullable<int> FeeArrangementApproverId { get; set; }
        public string SpecialFeeArrangementApproverComment { get; set; }
        public string SpecialFeeArrangementWaiverComment { get; set; }
        public Nullable<bool> IsSpecialFeeArrangementApproved { get; set; }
        public Nullable<bool> IsThirdPartyInvoices { get; set; }
        public string ThirdPartyInvoicesDetails { get; set; }
        public Nullable<bool> IsCostOverrides { get; set; }
        public Nullable<int> CostOverridesTypeId { get; set; }
        public Nullable<decimal> PhotocopyCostOverride { get; set; }
        public Nullable<decimal> FaxCostOverrides { get; set; }
        public Nullable<decimal> SecretaryCostOverrides { get; set; }
        public Nullable<decimal> WordProcessingCostOverrides { get; set; }
        public Nullable<decimal> ComputerResearchCostOverrides { get; set; }
        public string OverrideOtherDescription { get; set; }
        public Nullable<bool> IsBillingInstructions { get; set; }
        public string BillingInstructions { get; set; }
        public Nullable<int> EbillingVendorTypeId { get; set; }
        public string EbillingVendorOther { get; set; }
        public string RetainerRequestorComment { get; set; }
        public string SpecialFeeArrangementRequestorComment { get; set; }
        public string BillRateDescription { get; set; }
        public string DisbRateDescription { get; set; }
    
        public virtual BillingDetail BillingDetail { get; set; }
        public virtual Matter1 Matter1 { get; set; }
        public virtual BillFormat BillFormat { get; set; }
        public virtual CostOverridesType CostOverridesType { get; set; }
        public virtual DisbRate DisbRate { get; set; }
        public virtual Division Division { get; set; }
        public virtual EbillingVendorType EbillingVendorType { get; set; }
        public virtual FeesArrangement FeesArrangement { get; set; }
        public virtual FeesRetainerType FeesRetainerType { get; set; }
        public virtual FeesSpecialArrangement FeesSpecialArrangement { get; set; }
        public virtual FeesType FeesType { get; set; }
        public virtual MatterCategory MatterCategory { get; set; }
        public virtual PrebillFormat PrebillFormat { get; set; }
        public virtual TaxJurisdiction TaxJurisdiction { get; set; }
    }
}
