//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingDetail()
        {
            this.Matter2 = new HashSet<Matter2>();
        }
    
        public int Id { get; set; }
        public int RequestId { get; set; }
        public Nullable<int> BillRateId { get; set; }
        public Nullable<int> BillFrequencyId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
    
        public virtual BillFrequency BillFrequency { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Request Request { get; set; }
        public virtual BillingDetail1 BillingDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matter2> Matter2 { get; set; }
    }
}
