//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ContactOwner = new HashSet<ContactOwner>();
            this.RelatedParty = new HashSet<RelatedParty>();
            this.WaiverOwner = new HashSet<WaiverOwner>();
            this.Client1 = new HashSet<Client1>();
            this.Matter = new HashSet<Matter>();
        }
    
        public int Id { get; set; }
        public string ClientCode { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string LongName { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public int ClassificationId { get; set; }
        public int CloseNoteId { get; set; }
        public int ClientTypeId { get; set; }
        public bool FlagMainGroup { get; set; }
        public int OfficeId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public int StandardPartyId { get; set; }
        public string WarnNewMatterNote { get; set; }
        public string ProhibitNewContentCreationNote { get; set; }
        public bool NeedCloseAllMatters { get; set; }
        public bool NeedWarnNewMatter { get; set; }
        public bool IsProhibitedNewContentCreation { get; set; }
        public bool HasEthicalWall { get; set; }
        public bool IsRepresentative { get; set; }
        public bool HasWaiver { get; set; }
        public bool HasAttachment { get; set; }
        public bool HasComment { get; set; }
        public bool HasWaiverInternal { get; set; }
        public bool IsProbono { get; set; }
        public bool FlagCloseWhenLastActiveMatterClosed { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual ClientMatterCloseNote ClientMatterCloseNote { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual Department Department { get; set; }
        public virtual Office Office { get; set; }
        public virtual StandardParty StandardParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactOwner> ContactOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedParty> RelatedParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverOwner> WaiverOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client1> Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matter> Matter { get; set; }
    }
}
