//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client2()
        {
            this.ClientAlias = new HashSet<ClientAlias>();
            this.KYCVDirector = new HashSet<KYCVDirector>();
            this.KYCVShareholder = new HashSet<KYCVShareholder>();
        }
    
        public int Id { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<short> OriginalDocReviewed { get; set; }
        public Nullable<short> OriginalPersonDocReviewed { get; set; }
        public string AnnualFillingType { get; set; }
        public string OriginalDocNote { get; set; }
        public string IdentificationNo { get; set; }
        public string Occupation { get; set; }
        public string PlaceOfIssue { get; set; }
        public Nullable<bool> IsActingForThirdParty { get; set; }
        public Nullable<bool> IsInvolve { get; set; }
        public Nullable<bool> IsFinePayment { get; set; }
        public Nullable<bool> IsFundsWithinExemptions { get; set; }
        public Nullable<bool> IsFinancialPublicIssuer { get; set; }
        public Nullable<bool> IsFundsPaid { get; set; }
        public Nullable<bool> IsFromFinancialInstitution { get; set; }
        public Nullable<bool> IsFromOfficer { get; set; }
        public Nullable<bool> IsFromPursuantCourtOrder { get; set; }
        public Nullable<bool> IsFromPublicBody { get; set; }
        public Nullable<bool> IsFromProfessionalFees { get; set; }
        public Nullable<bool> IsFromReportingIssuer { get; set; }
        public Nullable<bool> IsFromSettlement { get; set; }
        public Nullable<bool> IsFromTrustAccount { get; set; }
        public Nullable<bool> IsOrganization { get; set; }
        public Nullable<bool> IsOnRestrictedList { get; set; }
        public Nullable<bool> IsPubliclyTraded { get; set; }
        public Nullable<bool> IsToFinancialInstitution { get; set; }
        public Nullable<bool> IsToPublicBody { get; set; }
        public Nullable<bool> IsToReportingIssuer { get; set; }
        public Nullable<bool> IsToPursuantCourtOrder { get; set; }
        public Nullable<bool> IsToSettlement { get; set; }
        public Nullable<bool> IsToProfessionalFees { get; set; }
        public Nullable<bool> IsVerifiedByDocId { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsBlist { get; set; }
        public Nullable<int> AccountReceivable { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public string ReportingName { get; set; }
        public Nullable<int> ClientTypeId { get; set; }
        public string ExternalContactId { get; set; }
        public Nullable<bool> IsAccountReceivable { get; set; }
        public Nullable<decimal> AccountReceivableAmount { get; set; }
        public Nullable<int> MatterId { get; set; }
        public string AddedOnStep { get; set; }
        public Nullable<bool> IsAPartner { get; set; }
        public Nullable<bool> IsRBCClient { get; set; }
        public Nullable<bool> IsCIBCClient { get; set; }
        public string DocNumScanned { get; set; }
        public string DocNumVerification { get; set; }
        public string DocNumPersonVerification { get; set; }
        public string RestrictedMatter { get; set; }
        public string ExternalState { get; set; }
        public string ExternalEntityType { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<int> VerifiedById { get; set; }
        public Nullable<int> IdentifiedById { get; set; }
        public Nullable<System.DateTime> IdentifiedOn { get; set; }
        public string BestEffortFailedDescription { get; set; }
        public string BillingArrangement { get; set; }
        public Nullable<bool> IsAffiliated { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string IndustryDescription { get; set; }
        public Nullable<int> AreaIndustryId { get; set; }
        public Nullable<bool> IsMunicipal { get; set; }
        public Nullable<int> PartyPositionId { get; set; }
        public Nullable<int> PartyRelationId { get; set; }
        public Nullable<int> OwnershipId { get; set; }
        public Nullable<int> TypeOfBusinessId { get; set; }
        public Nullable<int> RefferById { get; set; }
        public string RefferByDescription { get; set; }
        public Nullable<System.DateTime> ReprieveDate { get; set; }
        public Nullable<bool> HasBillingContact { get; set; }
        public Nullable<bool> HasHomeContact { get; set; }
        public string PartyPositionNotes { get; set; }
        public string PartyRelationNotes { get; set; }
        public Nullable<int> RelationshipLawyerId { get; set; }
        public string BillingInstructions { get; set; }
        public string EBILLCODES { get; set; }
        public Nullable<bool> IsMatterCategoryVisible { get; set; }
        public Nullable<bool> IsKYCVDirectorChanged { get; set; }
        public Nullable<bool> IsKYCVShareholderChanged { get; set; }
        public string DocumentScannedAuthorizedKV64 { get; set; }
        public string DocumentScannedKV63 { get; set; }
        public string DocumentLatestVerificationKV60 { get; set; }
        public string DocumentLatestVerificationAuthorizedKV61 { get; set; }
        public string BusinessActivity { get; set; }
    
        public virtual User User { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual PartyPosition1 PartyPosition1 { get; set; }
        public virtual PartyRelation1 PartyRelation1 { get; set; }
        public virtual Client1 Client1 { get; set; }
        public virtual Matter1 Matter1 { get; set; }
        public virtual AreaIndustry AreaIndustry { get; set; }
        public virtual EntityType1 EntityType1 { get; set; }
        public virtual OwnershipType OwnershipType { get; set; }
        public virtual RefferBy RefferBy { get; set; }
        public virtual TypeOfBusiness TypeOfBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAlias> ClientAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYCVDirector> KYCVDirector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYCVShareholder> KYCVShareholder { get; set; }
    }
}
