//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictSearch
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public string Entity { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<int> FeeArrangementId { get; set; }
        public string Code { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
