//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public string SystemId { get; set; }
        public string ComponentId { get; set; }
        public string CategoryId { get; set; }
        public string SettingId { get; set; }
        public string SettingVal { get; set; }
        public string SettingDescr { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    }
}
