//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictsResult
    {
        public int Id { get; set; }
        public Nullable<bool> IsConflictResolved { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> MatterId { get; set; }
        public Nullable<int> PartyId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string ConflictReport { get; set; }
        public string ClientIssue { get; set; }
        public string PartyIssue { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Client1 Client1 { get; set; }
        public virtual Client1 Client11 { get; set; }
        public virtual Matter1 Matter1 { get; set; }
        public virtual Request Request { get; set; }
    }
}
