//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactOwner
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int ContactOwnerTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StandardPartyId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> MatterId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual ContactOwnerType ContactOwnerType { get; set; }
        public virtual Client Client { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual Office Office { get; set; }
        public virtual StandardParty StandardParty { get; set; }
    }
}
