//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hold()
        {
            this.Acknowledgement = new HashSet<Acknowledgement>();
            this.Attachment2 = new HashSet<Attachment2>();
            this.ClientMatter = new HashSet<ClientMatter>();
            this.HoldSilo = new HashSet<HoldSilo>();
            this.Stakeholder = new HashSet<Stakeholder>();
            this.Timekeeper = new HashSet<Timekeeper>();
        }
    
        public int Id { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Name { get; set; }
        public int HoldTypeId { get; set; }
        public int RequestorId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool IsCollection { get; set; }
        public Nullable<System.DateTime> CollectionDateFrom { get; set; }
        public Nullable<System.DateTime> CollectionDateTo { get; set; }
        public bool IsInterview { get; set; }
        public bool IsAutoMonitor { get; set; }
        public Nullable<int> InterviewTemplateId { get; set; }
        public string PreservationOrder { get; set; }
        public string Notes { get; set; }
        public string Reason { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acknowledgement> Acknowledgement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment2> Attachment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMatter> ClientMatter { get; set; }
        public virtual HoldType HoldType { get; set; }
        public virtual InterviewTemplate InterviewTemplate { get; set; }
        public virtual HoldStatus HoldStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoldSilo> HoldSilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stakeholder> Stakeholder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timekeeper> Timekeeper { get; set; }
    }
}
