//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldList
    {
        public string Status { get; set; }
        public string HoldType { get; set; }
        public string Requestor { get; set; }
        public int Id { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Name { get; set; }
        public int HoldTypeId { get; set; }
        public int RequestorId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool IsCollection { get; set; }
        public Nullable<System.DateTime> CollectionDateFrom { get; set; }
        public Nullable<System.DateTime> CollectionDateTo { get; set; }
        public bool IsInterview { get; set; }
        public bool IsAutoMonitor { get; set; }
        public Nullable<int> InterviewTemplateId { get; set; }
        public string PreservationOrder { get; set; }
        public string Notes { get; set; }
        public string Reason { get; set; }
    }
}
