//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldSilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoldSilo()
        {
            this.SiloCustodian = new HashSet<SiloCustodian>();
            this.SiloDataSteward = new HashSet<SiloDataSteward>();
            this.SiloQuestion = new HashSet<SiloQuestion>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int HoldId { get; set; }
        public int TimekeeperId { get; set; }
        public string Name { get; set; }
        public Nullable<int> StandardSiloId { get; set; }
        public int Weight { get; set; }
        public Nullable<int> CollectionTimeValue { get; set; }
        public Nullable<int> CollectionTimeUnitId { get; set; }
        public string Location { get; set; }
        public Nullable<int> ResponsibleCustodianId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual CollectionTimeUnit CollectionTimeUnit { get; set; }
        public virtual Hold Hold { get; set; }
        public virtual StandardSilo StandardSilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloCustodian> SiloCustodian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloDataSteward> SiloDataSteward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloQuestion> SiloQuestion { get; set; }
    }
}
