//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstanceMetadataChangesTable
    {
        public long SurrogateInstanceId { get; set; }
        public long ChangeTime { get; set; }
        public byte EncodingOption { get; set; }
        public byte[] Change { get; set; }
    }
}
