//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationTemplate
    {
        public int IntegraTypeId { get; set; }
        public string IntegraSettId { get; set; }
        public string IntegraSettType { get; set; }
        public string IntegraSettDefVal { get; set; }
        public string IntegraSettDesc { get; set; }
    
        public virtual IntegrationType IntegrationType { get; set; }
    }
}
