//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeysTable
    {
        public System.Guid Id { get; set; }
        public long SurrogateKeyId { get; set; }
        public Nullable<long> SurrogateInstanceId { get; set; }
        public Nullable<byte> EncodingOption { get; set; }
        public byte[] Properties { get; set; }
        public Nullable<bool> IsAssociated { get; set; }
    }
}
