//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KycList2
    {
        public int ProcessInstanceId { get; set; }
        public int ProcessInstanceIsDeleted { get; set; }
        public int ProcessInstanceCreatedById { get; set; }
        public System.DateTime ProcessInstanceCreatedOn { get; set; }
        public Nullable<int> ProcessInstanceUpdatedById { get; set; }
        public Nullable<System.DateTime> ProcessInstanceUpdatedOn { get; set; }
        public string ProcessInstanceName { get; set; }
        public string ProcessInstanceNotes { get; set; }
        public int ProcessInstanceProcessId { get; set; }
        public int ProcessInstanceStatusId { get; set; }
        public int ProcessInstanceDocumentInstanceId { get; set; }
        public Nullable<int> ProcessInstanceParentId { get; set; }
        public Nullable<System.Guid> ProcessInstanceWorkflowInstanceGUID { get; set; }
        public Nullable<int> ProcessInstanceResultId { get; set; }
        public int ActivityInstanceId { get; set; }
        public int ActivityInstanceIsDeleted { get; set; }
        public int ActivityInstanceCreatedById { get; set; }
        public System.DateTime ActivityInstanceCreatedOn { get; set; }
        public Nullable<int> ActivityInstanceUpdatedById { get; set; }
        public Nullable<System.DateTime> ActivityInstanceUpdatedOn { get; set; }
        public string ActivityInstanceCode { get; set; }
        public string ActivityInstanceName { get; set; }
        public string ActivityInstanceNotes { get; set; }
        public int ActivityInstanceActivityId { get; set; }
        public int ActivityInstanceProcessInstanceId { get; set; }
        public int ActivityInstanceStatusId { get; set; }
        public int TaskId { get; set; }
        public int TaskIsDeleted { get; set; }
        public int TaskCreatedById { get; set; }
        public System.DateTime TaskCreatedOn { get; set; }
        public int TaskUpdatedById { get; set; }
        public System.DateTime TaskUpdatedOn { get; set; }
        public string TaskName { get; set; }
        public string TaskNotes { get; set; }
        public int TaskActivityInstanceId { get; set; }
        public int TaskParticipantId { get; set; }
        public int TaskUserId { get; set; }
        public int TaskStatusId { get; set; }
        public Nullable<int> TaskParentId { get; set; }
        public int TaskHasActions { get; set; }
    }
}
