//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockOwnersTable
    {
        public System.Guid Id { get; set; }
        public long SurrogateLockOwnerId { get; set; }
        public System.DateTime LockExpiration { get; set; }
        public Nullable<System.Guid> WorkflowHostType { get; set; }
        public string MachineName { get; set; }
        public bool EnqueueCommand { get; set; }
        public bool DeletesInstanceOnCompletion { get; set; }
        public byte[] PrimitiveLockOwnerData { get; set; }
        public byte[] ComplexLockOwnerData { get; set; }
        public byte[] WriteOnlyPrimitiveLockOwnerData { get; set; }
        public byte[] WriteOnlyComplexLockOwnerData { get; set; }
        public Nullable<byte> EncodingOption { get; set; }
    }
}
