//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatterDate
    {
        public int Id { get; set; }
        public int MatterId { get; set; }
        public int MatterDateTypeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DateNote { get; set; }
        public string DateEmail { get; set; }
        public bool IsEvent { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual DateType DateType { get; set; }
        public virtual Matter Matter { get; set; }
    }
}
