//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatterRole
    {
        public int MatterId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
    
        public virtual PartyRole PartyRole { get; set; }
        public virtual Matter Matter { get; set; }
    }
}
