//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatterAttorney
    {
        public int Id { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int MatterId { get; set; }
        public int AttorneyId { get; set; }
        public int AttorneyTypeId { get; set; }
        public double AttorneyPercent { get; set; }
        public Nullable<int> AttorneyTime { get; set; }
        public Nullable<System.DateTime> AttorneyDate { get; set; }
        public string Comment { get; set; }
        public bool IsFormer { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual AttorneyType AttorneyType { get; set; }
        public virtual Matter Matter { get; set; }
    }
}
