//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matter()
        {
            this.SearchRequest = new HashSet<SearchRequest>();
            this.SearchResult_COI = new HashSet<SearchResult_COI>();
            this.ContactOwner = new HashSet<ContactOwner>();
            this.Matter1 = new HashSet<Matter>();
            this.MatterAnalystNote = new HashSet<MatterAnalystNote>();
            this.MatterAttachment = new HashSet<MatterAttachment>();
            this.MatterAttorney = new HashSet<MatterAttorney>();
            this.MatterBill = new HashSet<MatterBill>();
            this.MatterComment = new HashSet<MatterComment>();
            this.MatterCountry = new HashSet<MatterCountry>();
            this.MatterDate = new HashSet<MatterDate>();
            this.MatterDIT = new HashSet<MatterDIT>();
            this.MatterReference = new HashSet<MatterReference>();
            this.MatterRole = new HashSet<MatterRole>();
            this.RelatedParty = new HashSet<RelatedParty>();
            this.WaiverOwner = new HashSet<WaiverOwner>();
            this.Matter11 = new HashSet<Matter1>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string MatterCode { get; set; }
        public Nullable<int> ParentMatterId { get; set; }
        public int EntityTypeId { get; set; }
        public int ChildrenCount { get; set; }
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string LongName { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public int CloseNoteId { get; set; }
        public int MatterTypeId { get; set; }
        public int OfficeId { get; set; }
        public int DepartmentId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public bool HasEthicalWall { get; set; }
        public bool HasWaiver { get; set; }
        public bool HasAttachment { get; set; }
        public bool HasComment { get; set; }
        public bool HasWaiverInternal { get; set; }
        public bool IsProbono { get; set; }
        public bool IsConfidential { get; set; }
        public string FlagLegacy { get; set; }
    
        public virtual ClientMatterCloseNote ClientMatterCloseNote { get; set; }
        public virtual Department Department { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual MatterType MatterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchRequest> SearchRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult_COI> SearchResult_COI { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactOwner> ContactOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matter> Matter1 { get; set; }
        public virtual Matter Matter2 { get; set; }
        public virtual MatterStatus MatterStatus { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterAnalystNote> MatterAnalystNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterAttachment> MatterAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterAttorney> MatterAttorney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterBill> MatterBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterComment> MatterComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterCountry> MatterCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterDate> MatterDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterDIT> MatterDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterReference> MatterReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatterRole> MatterRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedParty> RelatedParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverOwner> WaiverOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matter1> Matter11 { get; set; }
    }
}
