//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatterComment
    {
        public int Id { get; set; }
        public int MatterId { get; set; }
        public string Comment { get; set; }
        public int CommentTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public bool IsSearchable { get; set; }
        public int LocaleId { get; set; }
    
        public virtual CommentType CommentType { get; set; }
        public virtual Locale Locale { get; set; }
        public virtual Matter Matter { get; set; }
    }
}
