//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matter2
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IsOnRestrictedList { get; set; }
        public Nullable<int> ExternalId { get; set; }
        public Nullable<bool> HasConflict { get; set; }
        public Nullable<bool> HasPotentialConflict { get; set; }
        public Nullable<bool> IsAnyIndividuals { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<int> BillingDetailId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string RestrictedMatter { get; set; }
        public Nullable<bool> IsPubliclyTraded { get; set; }
        public string ExternalState { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<int> MatterNatureId { get; set; }
        public string ConflictDescription { get; set; }
        public string DeadlineDescription { get; set; }
        public Nullable<int> DeadlineTypeId { get; set; }
        public Nullable<int> BillingOfficeId { get; set; }
        public Nullable<bool> IsSameAsClientContact { get; set; }
        public Nullable<bool> IsEthicalWall { get; set; }
        public string EthicalWallDescription { get; set; }
        public Nullable<bool> IsAttorneyOfRecord { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> ReprieveDate { get; set; }
        public string PositionalConflictDescription { get; set; }
        public Nullable<int> EngagementLetterStatusId { get; set; }
        public string ModelMatter { get; set; }
        public Nullable<bool> HasIssueBeenResolved { get; set; }
        public Nullable<bool> IsEthicaWall { get; set; }
        public Nullable<bool> IsConsent { get; set; }
        public Nullable<bool> IsOther { get; set; }
        public string OtherDescription { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<System.DateTime> OpenOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ClosedById { get; set; }
        public Nullable<int> OpenById { get; set; }
        public Nullable<int> ModifiedById { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual BillingDetail BillingDetail { get; set; }
        public virtual Client1 Client1 { get; set; }
        public virtual Matter1 Matter1 { get; set; }
        public virtual DeadlineType DeadlineType { get; set; }
        public virtual MatterNature MatterNature { get; set; }
        public virtual MatterStatus1 MatterStatus1 { get; set; }
    }
}
