//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageOffice
    {
        public int Id { get; set; }
        public int LocaleId { get; set; }
        public int MsgId { get; set; }
        public int OfficeId { get; set; }
        public string MsgText { get; set; }
        public string MsgDesc { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual Locale Locale { get; set; }
        public virtual Message Message { get; set; }
        public virtual Office Office { get; set; }
    }
}
