//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRecipient
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int MessageId { get; set; }
        public int NotificationRecipientId { get; set; }
        public int RecipientUserId { get; set; }
        public Nullable<int> AcknowledgementSentReminders { get; set; }
        public Nullable<bool> AcknowledgementRecieved { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Message1 Message1 { get; set; }
        public virtual NotificationRecipient NotificationRecipient { get; set; }
    }
}
