//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message1()
        {
            this.Message11 = new HashSet<Message1>();
            this.MessageRecipient = new HashSet<MessageRecipient>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int NotificationId { get; set; }
        public int EventId { get; set; }
        public int MessageStatusId { get; set; }
        public string CompiledSubject { get; set; }
        public string CompiledMessage { get; set; }
        public Nullable<bool> IsAcknowledgement { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> AcknowledgementStatusId { get; set; }
    
        public virtual EventLog EventLog { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual AcknowledgementStatus AcknowledgementStatus { get; set; }
        public virtual MessageStatus MessageStatus { get; set; }
        public virtual Notification Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message1> Message11 { get; set; }
        public virtual Message1 Message12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageRecipient> MessageRecipient { get; set; }
    }
}
