//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelDetail
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int ModelId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public int FieldTypeId { get; set; }
        public bool AllowFilter { get; set; }
        public string LookupTableName { get; set; }
        public string LookupFieldIdName { get; set; }
        public string LookupFieldDescName { get; set; }
        public bool IsSubreportLink { get; set; }
        public bool AllowEmptyLinkValue { get; set; }
        public bool IsLinkToParent { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual FieldType FieldType { get; set; }
        public virtual Model Model { get; set; }
    }
}
