//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int NotificationId { get; set; }
        public int LocaleId { get; set; }
        public int MimeTypeId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsAcknowledgement { get; set; }
    
        public virtual Locale Locale { get; set; }
        public virtual MimeType MimeType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
