//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRecipient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationRecipient()
        {
            this.MessageRecipient = new HashSet<MessageRecipient>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int NotificationId { get; set; }
        public int PositionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AcknowledgementTypeId { get; set; }
        public Nullable<int> AcknowledgementReminders { get; set; }
        public string AcknowledgementReminderInterval { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual AcknowledgementType AcknowledgementType { get; set; }
        public virtual EmailPosition EmailPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageRecipient> MessageRecipient { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
