//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyRule
    {
        public int Id { get; set; }
        public int NotifyTypeCode { get; set; }
        public string NotifyHeader { get; set; }
        public string Param1Val { get; set; }
        public string Param2Val { get; set; }
        public string Param3Val { get; set; }
        public Nullable<int> AckTextMsgCodeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    }
}
