//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationUnit()
        {
            this.OrganizationUnit1 = new HashSet<OrganizationUnit>();
            this.SiloOrgUnit = new HashSet<SiloOrgUnit>();
        }
    
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int LevelId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool IsPrimary { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> PracticeCodeId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Department2 Department2 { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Office Office { get; set; }
        public virtual OrganizationLevel OrganizationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationUnit> OrganizationUnit1 { get; set; }
        public virtual OrganizationUnit OrganizationUnit2 { get; set; }
        public virtual Person Person { get; set; }
        public virtual PracticeCode PracticeCode { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloOrgUnit> SiloOrgUnit { get; set; }
    }
}
