//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party1
    {
        public int Id { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> ClientTypeId { get; set; }
        public bool IsOrganization { get; set; }
        public Nullable<bool> IsOnRestrictedList { get; set; }
        public Nullable<bool> IsConflictParty { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ClientType3 ClientType3 { get; set; }
    }
}
