//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyMatrix
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int PartyTreeId { get; set; }
        public int FromPartyId { get; set; }
        public int ToPartyId { get; set; }
        public int RelationId { get; set; }
        public decimal RelationWeight { get; set; }
        public int RelationDepth { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual PartyTree PartyTree { get; set; }
        public virtual PartyRelation1 PartyRelation1 { get; set; }
    }
}
