//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.AddressOwner = new HashSet<AddressOwner>();
            this.OrganizationUnit = new HashSet<OrganizationUnit>();
            this.PersonAlias = new HashSet<PersonAlias>();
        }
    
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string SalutationFormal { get; set; }
        public string SalutationInformal { get; set; }
        public string SalutationSpecial { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<int> PrefixNameId { get; set; }
        public Nullable<int> SuffixNameId { get; set; }
        public Nullable<int> HonorificNameId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> PersonStatusId { get; set; }
        public Nullable<int> JobTitleId { get; set; }
        public Nullable<int> JobPositionId { get; set; }
        public string Room { get; set; }
        public string Floor { get; set; }
        public int Id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressOwner> AddressOwner { get; set; }
        public virtual Attorney1 Attorney1 { get; set; }
        public virtual Gender1 Gender1 { get; set; }
        public virtual HonorificName HonorificName { get; set; }
        public virtual JobPosition JobPosition { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual MaritalStatus MaritalStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationUnit> OrganizationUnit { get; set; }
        public virtual PersonStatus PersonStatus { get; set; }
        public virtual PrefixName PrefixName { get; set; }
        public virtual SuffixName SuffixName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAlias> PersonAlias { get; set; }
        public virtual Person1 Person1 { get; set; }
    }
}
