//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pitch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pitch()
        {
            this.PitchAttorneyRole = new HashSet<PitchAttorneyRole>();
            this.PitchParty = new HashSet<PitchParty>();
            this.PitchSearchLog = new HashSet<PitchSearchLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AttorneyPitchTypeId { get; set; }
        public Nullable<int> AttorneyPitchStatusId { get; set; }
        public string Title { get; set; }
        public string NickName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsNotSearchable { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Reserved1 { get; set; }
        public string Reserved2 { get; set; }
        public Nullable<System.DateTime> Reserved3 { get; set; }
        public Nullable<int> Reserved4 { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual AttorneyPitchStatus AttorneyPitchStatus { get; set; }
        public virtual AttorneyPitchType AttorneyPitchType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchAttorneyRole> PitchAttorneyRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchParty> PitchParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchSearchLog> PitchSearchLog { get; set; }
    }
}
