//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchParty
    {
        public int Id { get; set; }
        public int PitchId { get; set; }
        public int StandardPartyId { get; set; }
        public Nullable<int> C__prty_id { get; set; }
        public Nullable<int> CodeId { get; set; }
        public string CnComment { get; set; }
        public string CnOther { get; set; }
        public string Reserved1 { get; set; }
        public string Reserved2 { get; set; }
        public Nullable<System.DateTime> Reserved3 { get; set; }
        public Nullable<int> Reserved4 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual Pitch Pitch { get; set; }
        public virtual StandardParty StandardParty { get; set; }
    }
}
