//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireInstance
    {
        public int QuestionnaireId { get; set; }
        public int RequestId { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsListed { get; set; }
        public string ExchangeName { get; set; }
        public string ListedParentName { get; set; }
        public Nullable<bool> IsRated { get; set; }
        public string AgencyName { get; set; }
        public Nullable<bool> IsEvidenceObtained { get; set; }
        public string EvidenceName { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsCertified { get; set; }
        public Nullable<int> CertifiedById { get; set; }
        public Nullable<System.DateTime> CertifiedOn { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual Request Request { get; set; }
    }
}
