//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelatedParty()
        {
            this.SearchResult_COI = new HashSet<SearchResult_COI>();
            this.RelatedPartyAlert = new HashSet<RelatedPartyAlert>();
            this.RelatedPartyComment = new HashSet<RelatedPartyComment>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> MatterId { get; set; }
        public int StandartPartyId { get; set; }
        public int PartyPosId { get; set; }
        public int ParentRelatedPartyId { get; set; }
        public int PartyRelId { get; set; }
        public bool HasAlert { get; set; }
        public bool HasEthicalWallAssigned { get; set; }
        public bool HasWaiver { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual PartyPosition PartyPosition { get; set; }
        public virtual PartyRelation PartyRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult_COI> SearchResult_COI { get; set; }
        public virtual Client Client { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual StandardParty StandardParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartyAlert> RelatedPartyAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartyComment> RelatedPartyComment { get; set; }
    }
}
