//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestUser1
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int RequestId { get; set; }
        public int UserId { get; set; }
        public int RequestUserTypeId { get; set; }
        public string ActivityCode { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public string RelationshipNotes { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual AttorneyRelationship AttorneyRelationship { get; set; }
        public virtual Request1 Request1 { get; set; }
        public virtual RequestUserType RequestUserType { get; set; }
    }
}
