//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRequestTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchRequestTerm()
        {
            this.SearchResult_COI = new HashSet<SearchResult_COI>();
        }
    
        public int Id { get; set; }
        public int SearchRequestId { get; set; }
        public string Term { get; set; }
        public string EntityCategory { get; set; }
        public bool HasAlert { get; set; }
        public string LineName { get; set; }
        public string PartyPosDesc { get; set; }
        public string PartyRelDesc { get; set; }
        public int PartyPosId { get; set; }
        public int PartyRelId { get; set; }
        public decimal TermOrder { get; set; }
        public string TermComment { get; set; }
        public string TermStatus { get; set; }
        public string DunsNum { get; set; }
        public string ParentDunsNum { get; set; }
        public string UltimateDunsNum { get; set; }
        public string CsSrTermSourceId { get; set; }
        public string SrLingOption { get; set; }
        public Nullable<int> ParentSearchRequestTermId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual PartyPosition PartyPosition { get; set; }
        public virtual PartyRelation PartyRelation { get; set; }
        public virtual SearchRequest SearchRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult_COI> SearchResult_COI { get; set; }
    }
}
