//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult_COI
    {
        public int HitId { get; set; }
        public int SearchRequestId { get; set; }
        public int ClientMatterId { get; set; }
        public int ClientMatterPartyId { get; set; }
        public int AliasStandardPartyId { get; set; }
        public int SearchRequestTermId { get; set; }
        public int StandardPartyId { get; set; }
        public bool IsSelected { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
        public int SearchUser { get; set; }
        public string MatchSource { get; set; }
        public int SrTermIdSuppress { get; set; }
        public string HitAnnotation { get; set; }
        public int FilterLevel { get; set; }
        public int HitEntityId { get; set; }
        public int TechScore { get; set; }
        public int BusScore { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual SearchRequest SearchRequest { get; set; }
        public virtual SearchRequestTerm SearchRequestTerm { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual RelatedParty RelatedParty { get; set; }
        public virtual StandardParty StandardParty { get; set; }
    }
}
