//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StandardParty()
        {
            this.SearchResult_COI = new HashSet<SearchResult_COI>();
            this.Client = new HashSet<Client>();
            this.ContactOwner = new HashSet<ContactOwner>();
            this.CorporateTreeHierarchy = new HashSet<CorporateTreeHierarchy>();
            this.PitchParty = new HashSet<PitchParty>();
            this.RelatedParty = new HashSet<RelatedParty>();
            this.CorporateTreeMember = new HashSet<CorporateTreeMember>();
            this.StandardPartyAlert = new HashSet<StandardPartyAlert>();
            this.StandardPartyAlias = new HashSet<StandardPartyAlias>();
            this.StandardPartyComment = new HashSet<StandardPartyComment>();
            this.StandardPartyIndustry = new HashSet<StandardPartyIndustry>();
            this.StandardPartyLink = new HashSet<StandardPartyLink>();
            this.StandardPartyLink1 = new HashSet<StandardPartyLink>();
            this.WaiverGrant = new HashSet<WaiverGrant>();
            this.Party = new HashSet<Party>();
        }
    
        public int Id { get; set; }
        public string StandardPartyCode { get; set; }
        public int OwnerApplicationDomainId { get; set; }
        public string Name { get; set; }
        public string PrefixName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SuffixName { get; set; }
        public bool HasEthicalWall { get; set; }
        public int StandardPartyStatusId { get; set; }
        public bool IsOrganization { get; set; }
        public int IsDeleted { get; set; }
        public string AbbrName { get; set; }
        public string DunsNum { get; set; }
        public string ParentDunsNum { get; set; }
        public int ClassificationId { get; set; }
        public bool HasAlert { get; set; }
        public bool HasAlias { get; set; }
        public bool IsCorporateTreeMember { get; set; }
        public bool IsPrivate { get; set; }
        public int OfficeId { get; set; }
        public int ReferralSourceId { get; set; }
        public string UltimateDunsNum { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CloseNote { get; set; }
        public string DunsLocType { get; set; }
        public int DunsNumMembers { get; set; }
        public int DunsNumEmpl { get; set; }
        public Nullable<decimal> DunsSales { get; set; }
        public int StandardPartyIdDunsCeo { get; set; }
        public bool ProhibitLinkage { get; set; }
        public bool HasLinks { get; set; }
        public string SysVal { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual ReferralSource ReferralSource { get; set; }
        public virtual StandardPartyStatus StandardPartyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResult_COI> SearchResult_COI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactOwner> ContactOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateTreeHierarchy> CorporateTreeHierarchy { get; set; }
        public virtual Office Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PitchParty> PitchParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedParty> RelatedParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateTreeMember> CorporateTreeMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyAlert> StandardPartyAlert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyAlias> StandardPartyAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyComment> StandardPartyComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyIndustry> StandardPartyIndustry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyLink> StandardPartyLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardPartyLink> StandardPartyLink1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverGrant> WaiverGrant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Party { get; set; }
    }
}
