//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList1
    {
        public Nullable<int> Id { get; set; }
        public int DocumentInstanceId { get; set; }
        public string TaskName { get; set; }
        public string UserGroup { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> HasActions { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ActivityInstanceId { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
