//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int DomainId { get; set; }
        public int HandlerId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> NextStartOn { get; set; }
        public string RecurrencyInterval { get; set; }
        public string StateData { get; set; }
    
        public virtual ApplicationDomain ApplicationDomain { get; set; }
        public virtual User User { get; set; }
        public virtual TaskHandler TaskHandler { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual User User1 { get; set; }
    }
}
