//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimekeeperList
    {
        public Nullable<int> Id { get; set; }
        public int HoldId { get; set; }
        public int TimekeeperId { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<bool> IsAutomatic { get; set; }
        public Nullable<int> CreatedById { get; set; }
    }
}
