//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedData
    {
        public int Id { get; set; }
        public int MatterNumber { get; set; }
        public int ExternalId_KI1a { get; set; }
        public Nullable<bool> Entity_Type_KI1b { get; set; }
        public string Client_Name_KI1 { get; set; }
        public string Occupation_KI3 { get; set; }
        public string Authorized_Person_KI17 { get; set; }
        public string Position_KI18 { get; set; }
        public string PhoneNo_KI19 { get; set; }
        public string IndClientName_KVI2 { get; set; }
        public string IndOccupation_KVI3 { get; set; }
        public string Buss_IdentNo_KI14 { get; set; }
        public string KI14IssuePlace_KI15 { get; set; }
        public string BL_Login_KVI5 { get; set; }
        public string BL_Name_KVI5A { get; set; }
        public string Industry_KI16 { get; set; }
        public string Bus_Address_KI4 { get; set; }
        public string City_KI6 { get; set; }
        public string State_KI7 { get; set; }
        public string ZipCode_KI21 { get; set; }
        public string Coutry_KI20 { get; set; }
        public string TepNo_KI12 { get; set; }
        public string Home_Add_KI8 { get; set; }
        public string Hom_City_KI10 { get; set; }
        public string Hom_State_KI11 { get; set; }
        public string Hom_ZipCode_KI23 { get; set; }
        public string Hom_Coutry_KI22 { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string Error { get; set; }
    }
}
