//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContact
    {
        public int Id { get; set; }
        public bool IsPrimary { get; set; }
        public int IsDeleted { get; set; }
        public string TelId { get; set; }
        public string TelNumber { get; set; }
        public string Email { get; set; }
        public int UserId { get; set; }
    }
}
