//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Waiver()
        {
            this.WaiverConstraint = new HashSet<WaiverConstraint>();
            this.WaiverGrant = new HashSet<WaiverGrant>();
            this.WaiverOwner = new HashSet<WaiverOwner>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> WaiverDateSigned { get; set; }
        public int AttorneyObtainedById { get; set; }
        public int SignedById { get; set; }
        public string WaiverSignature { get; set; }
        public string WaiverComment { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual Attorney Attorney1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverConstraint> WaiverConstraint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverGrant> WaiverGrant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaiverOwner> WaiverOwner { get; set; }
    }
}
