//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.BoxDb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaiverOwner
    {
        public int Id { get; set; }
        public int WaiverOwnerTypeId { get; set; }
        public int WaiverId { get; set; }
        public Nullable<int> MatterId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public decimal RecordId { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedById { get; set; }
    
        public virtual WaiverOwnerType WaiverOwnerType { get; set; }
        public virtual Client Client { get; set; }
        public virtual Matter Matter { get; set; }
        public virtual Waiver Waiver { get; set; }
    }
}
