//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenDbEntities : DbContext
    {
        public OpenDbEntities()
            : base("name=OpenDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TermCategory> TermCategories { get; set; }
        public DbSet<TermDataColumnType> TermDataColumnTypes { get; set; }
        public DbSet<TermDefinitionProperty> TermDefinitionProperties { get; set; }
        public DbSet<TermDefinitionPropertyImportanceLevel> TermDefinitionPropertyImportanceLevels { get; set; }
        public DbSet<TermDefinitionPropertyType> TermDefinitionPropertyTypes { get; set; }
        public DbSet<TermDefinition> TermDefinitions { get; set; }
        public DbSet<TermDocumentOrigin> TermDocumentOrigins { get; set; }
        public DbSet<TermDocument> TermDocuments { get; set; }
        public DbSet<TermDocumentScope> TermDocumentScopes { get; set; }
        public DbSet<TermDocumentStatus> TermDocumentStatuses { get; set; }
        public DbSet<TermDocumentType> TermDocumentTypes { get; set; }
        public DbSet<TermPropertyUnit> TermPropertyUnits { get; set; }
        public DbSet<TermPropertyValue> TermPropertyValues { get; set; }
        public DbSet<TermPropertyValueToComponent> TermPropertyValueToComponents { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<TermStatus> TermStatuses { get; set; }
    }
}
