//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermPropertyValue
    {
        public TermPropertyValue()
        {
            this.TermPropertyValueToComponents = new HashSet<TermPropertyValueToComponent>();
        }
    
        public int Id { get; set; }
        public int Property_Id { get; set; }
        public Nullable<int> Term_Id { get; set; }
        public string OriginalValue { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<decimal> DecimalValue { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<int> PropertyUnit_Id { get; set; }
    
        public virtual TermDefinitionProperty TermDefinitionProperty { get; set; }
        public virtual TermPropertyUnit TermPropertyUnit { get; set; }
        public virtual Term Term { get; set; }
        public virtual ICollection<TermPropertyValueToComponent> TermPropertyValueToComponents { get; set; }
    }
}
