//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDefinitionPropertyType
    {
        public TermDefinitionPropertyType()
        {
            this.TermDefinitionProperties = new HashSet<TermDefinitionProperty>();
            this.TermPropertyUnits = new HashSet<TermPropertyUnit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DataColumn { get; set; }
        public string Key { get; set; }
        public bool ConfigurableUnits { get; set; }
    
        public virtual TermDataColumnType TermDataColumnType { get; set; }
        public virtual ICollection<TermDefinitionProperty> TermDefinitionProperties { get; set; }
        public virtual ICollection<TermPropertyUnit> TermPropertyUnits { get; set; }
    }
}
