//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDocument
    {
        public TermDocument()
        {
            this.TermDocuments1 = new HashSet<TermDocument>();
            this.Terms = new HashSet<Term>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string Hash { get; set; }
        public int Status_Id { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy_Id { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
        public int LastModifiedBy_Id { get; set; }
        public Nullable<System.DateTime> EffectiveOn { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Matter_Id { get; set; }
        public int Component_Id { get; set; }
        public bool Reference { get; set; }
        public string Version { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public bool NotificationSent { get; set; }
        public bool ExcludeSubsidiaries { get; set; }
        public Nullable<System.Guid> SourceContentId { get; set; }
        public Nullable<System.Guid> PdfContentId { get; set; }
    
        public virtual ICollection<TermDocument> TermDocuments1 { get; set; }
        public virtual TermDocument TermDocument1 { get; set; }
        public virtual TermDocumentStatus TermDocumentStatus { get; set; }
        public virtual TermDocumentType TermDocumentType { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
    }
}
