//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDataColumnType
    {
        public TermDataColumnType()
        {
            this.TermDefinitionPropertyTypes = new HashSet<TermDefinitionPropertyType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TermDefinitionPropertyType> TermDefinitionPropertyTypes { get; set; }
    }
}
