//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.TermPropertyValues = new HashSet<TermPropertyValue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Definition_Id { get; set; }
        public int Document_Id { get; set; }
        public int Component_Id { get; set; }
        public string Positions { get; set; }
        public Nullable<System.DateTime> EffectiveOn { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public int NegotiationStatus_Id { get; set; }
        public string Notes { get; set; }
        public int Status_Id { get; set; }
        public bool Overridden { get; set; }
        public bool Atypical { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
    
        public virtual TermDefinition TermDefinition { get; set; }
        public virtual TermDocument TermDocument { get; set; }
        public virtual ICollection<TermPropertyValue> TermPropertyValues { get; set; }
        public virtual TermStatus TermStatus { get; set; }
    }
}
