//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermDocumentType
    {
        public TermDocumentType()
        {
            this.TermDocuments = new HashSet<TermDocument>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Origin_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Scope_Id { get; set; }
        public bool Reference { get; set; }
        public bool Required { get; set; }
        public string Key { get; set; }
    
        public virtual TermDocumentOrigin TermDocumentOrigin { get; set; }
        public virtual ICollection<TermDocument> TermDocuments { get; set; }
        public virtual TermDocumentScope TermDocumentScope { get; set; }
    }
}
