//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SD.EF.Sample.DataModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermCategory
    {
        public TermCategory()
        {
            this.TermCategories1 = new HashSet<TermCategory>();
            this.TermDefinitions = new HashSet<TermDefinition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Name { get; set; }
        public string ParentCategories { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<TermCategory> TermCategories1 { get; set; }
        public virtual TermCategory TermCategory1 { get; set; }
        public virtual ICollection<TermDefinition> TermDefinitions { get; set; }
    }
}
